spring.application:
  name: cfn-node

cfn:
  node:
    head: true
    local-resource-manager: com.github9triver.cfn.manager.K8sLocalResourceManager
  k8s:
    config-file: ""
    context: "docker-desktop"

grpc:
  port: 9090

server:
  port: 8081
